export const blogPosts = [
  {
    slug: "ai-generated-code-vulnerabilities-2026",
    title: "10 Most Common Security Mistakes in AI-Generated Code",
    excerpt: "AI coding assistants are changing how we build software, but they often introduce subtle security flaws. Learn the top 10 vulnerabilities they create and how to fix them.",
    category: "Security",
    readTime: "8 min read",
    date: "June 14, 2026",
    seoTitle: "AI generated code vulnerabilities | CodeAudit.dev",
    seoDescription: "Discover the top 10 security vulnerabilities found in AI-generated code and learn how to audit your vibe-coded applications to prevent data breaches.",
    content: `
AI coding assistants have revolutionized the speed at which we can build and ship software. Tools like GitHub Copilot, Cursor, and Claude are incredible companions for "vibe coding"—allowing developers to construct complex applications primarily through natural language prompts. However, this speed comes with a significant trade-off: security blind spots. 

Because LLMs are trained on vast amounts of public code (much of which is outdated or insecure), they frequently suggest implementations that look correct but contain subtle vulnerabilities. In this guide, we break down the 10 most common security mistakes in AI-generated code and show you how to identify and fix them.

## 1. Missing Input Validation on API Routes

One of the most frequent errors AI makes is assuming that incoming data is well-formed and safe. When asked to "create an endpoint to update user profiles," an AI will often generate the database update logic but completely skip validation.

\`\`\`typescript
// AI-generated (Unsafe)
app.post('/api/profile', async (req, res) => {
  const user = await db.users.update({ id: req.user.id }, req.body);
  res.json(user);
});
\`\`\`

**The Fix:** Always enforce a strict schema using libraries like Zod or Joi. Never pass \`req.body\` directly into a database query.

## 2. Hardcoded Secrets and API Keys

AI models love to generate code that "just works." When prompting for an integration with a third-party service like Stripe or AWS, the AI will frequently hardcode placeholder keys directly into the source file. If you aren't careful, you might replace those placeholders with real keys and commit them to version control.

**The Fix:** Use environment variables (\`process.env\`) exclusively. Use tools like CodeAudit to scan for exposed secrets before they reach your repository.

## 3. SQL Injection via String Interpolation

While ORMs have reduced the prevalence of SQL injection, AI models will still suggest raw SQL queries using string interpolation when asked to perform complex joins or dynamic filtering.

\`\`\`javascript
// AI-generated (Unsafe)
const query = \`SELECT * FROM users WHERE email = '\${req.body.email}'\`;
db.execute(query);
\`\`\`

**The Fix:** Always use parameterized queries or stick to your ORM's built-in query builders.

## 4. Insecure Direct Object References (IDOR)

When an AI builds a "fetch user data" endpoint, it typically relies entirely on the parameters provided in the request without verifying ownership.

\`\`\`typescript
// AI-generated (Unsafe)
app.get('/api/documents/:id', async (req, res) => {
  const doc = await db.documents.find(req.params.id);
  res.json(doc);
});
\`\`\`

**The Fix:** Always verify that the currently authenticated user has permission to access the requested resource. Check the document's \`owner_id\` against \`req.user.id\`.

## 5. Over-Permissive CORS Configurations

When an AI encounters a CORS error during development, its default solution is often the nuclear option: allowing all origins.

\`\`\`javascript
// AI-generated (Unsafe)
app.use(cors({ origin: '*' }));
\`\`\`

**The Fix:** Explicitly define the allowed origins. Only allow your production and staging domains.

## 6. Exposing Sensitive Data in Responses

AI-generated endpoints often return entire database rows directly to the client, inadvertently leaking password hashes, internal IDs, or other users' private data.

**The Fix:** Create specific Data Transfer Objects (DTOs) or use selection parameters to ensure only necessary fields are sent to the client.

## 7. Improper Error Handling Leaking Internal Logic

When prompted to add error handling, AI often catches exceptions and returns the raw error message to the client. This can expose stack traces, database schema details, or underlying infrastructure paths.

**The Fix:** Log the raw error internally, but return a generic, user-friendly error message to the client.

## 8. Missing Rate Limiting on Authentication Routes

Authentication endpoints generated by AI almost never include rate limiting, leaving your application vulnerable to credential stuffing and brute-force attacks.

**The Fix:** Implement strict rate limiting on all login, registration, and password reset endpoints.

## 9. Weak Cryptography and Hashing

When asked to hash a password or generate a token, AI models sometimes reach for outdated algorithms like MD5 or SHA-1 because they are heavily represented in older training data.

**The Fix:** Use bcrypt or Argon2 for password hashing, and rely on secure, standard libraries for token generation.

## 10. Disabled Row-Level Security (RLS)

If you use tools like Supabase, AI will often provide instructions or SQL to create tables without explicitly enabling and configuring Row-Level Security, leaving your database entirely open.

**The Fix:** Always enable RLS on every table and define explicit policies for read and write operations.

<br/>

Want CodeAudit to check your repo for these automatically? Join the waitlist and secure your AI-generated code before launch.

## Frequently Asked Questions

**Q: Are AI coding tools safe to use?**
A: Yes, but they should be treated as junior developers. Their output must be reviewed, tested, and audited before being deployed to production.

**Q: How can I catch these vulnerabilities automatically?**
A: CodeAudit.dev specializes in scanning repositories for these exact patterns, providing automated security reviews tailored for modern development workflows.

**Q: Does GitHub Copilot have built-in security features?**
A: Copilot includes some basic filtering, but it does not perform a comprehensive architectural or contextual security audit of your codebase.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "hardcoded-secrets-guide",
    title: "How to Find and Fix Hardcoded Secrets in Your Codebase",
    excerpt: "Hardcoded secrets are the leading cause of data breaches. Here is a comprehensive guide to identifying, removing, and preventing exposed API keys in your repository.",
    category: "Security",
    readTime: "7 min read",
    date: "June 12, 2026",
    seoTitle: "How to find hardcoded secrets | CodeAudit.dev",
    seoDescription: "Learn how to find and fix hardcoded secrets, API keys, and credentials in your codebase to prevent devastating security breaches.",
    content: `
Hardcoding secrets—API keys, database credentials, JWT signing keys, and cloud provider tokens—is one of the most dangerous and common security mistakes a developer can make. Once a secret is committed to a repository, it is considered compromised, even if the repository is private.

In this guide, we will explore why hardcoded secrets happen, how to find them in your existing codebase, and the steps required to permanently fix the issue.

## Why Do Secrets End Up in Code?

Most hardcoded secrets start innocently enough. You are testing a new API integration, you paste the key directly into your fetch function to "just see if it works," and you promise yourself you'll move it to an environment variable later. Fast forward three days, you commit the feature, and the key goes with it.

With the rise of AI coding assistants, this problem has multiplied. AIs often generate code with placeholder strings like \`"sk_live_12345"\`, and tired developers sometimes replace them with real keys directly in the file.

## How to Find Hardcoded Secrets

Finding secrets manually in a large codebase is nearly impossible. Attackers use automated tools to scan public repositories for key patterns within seconds of a commit. You need to use similar tools to protect yourself.

1. **Regex Scanning:** Most secrets follow a specific pattern. For example, Stripe live keys start with \`sk_live_\`, and AWS Access Keys typically start with \`AKIA\`. You can use tools like \`grep\` to search your codebase for these patterns.
2. **Automated Scanners:** Tools like CodeAudit.dev perform deep scans of your entire repository, looking not just for known patterns, but also utilizing high-entropy string detection to find custom passwords and obscure tokens.
3. **Pre-commit Hooks:** Set up tools like \`git-secrets\` or \`trufflehog\` to scan your commits locally before they are ever pushed to a remote server.

## The Fix: What to Do When You Find a Secret

If you discover a secret in your codebase, deleting the file or removing the line of code and committing the change is **not enough**. The secret will still exist in your Git history.

Here is the exact protocol to follow:

### Step 1: Rotate the Secret Immediately
Assume the secret is already compromised. Go to the provider (Stripe, AWS, Supabase, etc.) and generate a new key. Revoke the old key. This is the only way to guarantee your application is safe.

### Step 2: Move the Secret to Environment Variables
Update your code to read the configuration from environment variables.

\`\`\`typescript
// Bad
const stripe = new Stripe('sk_live_123456789');

// Good
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
\`\`\`

### Step 3: Update .gitignore
Ensure that your \`.env\` file is explicitly listed in your \`.gitignore\` file. You should only commit a \`.env.example\` file that contains empty variable names.

### Step 4: Scrub Your Git History (Optional but Recommended)
If the repository is private and the key has been rotated, the immediate threat is neutralized. However, it is best practice to scrub the secret from your history using a tool like BFG Repo-Cleaner or \`git filter-repo\`. Be warned: this rewrites your git history and will require all collaborators to force-pull.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: Are secrets safe if my GitHub repository is private?**
A: No. Private repositories can be accidentally made public, employee laptops can be compromised, and third-party integrations can leak data. Assume any committed secret is exposed.

**Q: Can I just delete the commit?**
A: Standard git commands like \`git revert\` or deleting the line only add a new commit. The secret remains fully accessible in the commit history. You must use history-rewriting tools.

**Q: How does CodeAudit handle secrets?**
A: CodeAudit scans your codebase for over 150 types of secrets, high-entropy strings, and common credential patterns, delivering actionable reports before you deploy.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "pre-launch-saas-security-checklist",
    title: "25-Point Pre-Launch Security Checklist for SaaS Founders",
    excerpt: "Don't launch your SaaS with glaring security holes. Use this comprehensive 25-point checklist to secure your application, database, and infrastructure.",
    category: "Security",
    readTime: "12 min read",
    date: "June 10, 2026",
    seoTitle: "Pre-launch security checklist SaaS | CodeAudit.dev",
    seoDescription: "The ultimate 25-point pre-launch security checklist for SaaS founders. Secure your authentication, database, and APIs before launching your product.",
    content: `
You've spent months building your SaaS. The marketing site is up, the waitlist is full, and you're ready to launch on Product Hunt. But before you flip the switch, you need to ensure your application is secure. 

A data breach in your first week can permanently destroy user trust. This 25-point checklist covers the essential security measures every SaaS founder must verify before launch.

## Authentication & Authorization

1. **Enforce Strong Passwords:** Require a minimum of 8-12 characters. Do not enforce arbitrary complexity rules (like "must contain a special character"); length is more important.
2. **Implement Rate Limiting:** Apply strict rate limits to \`/login\`, \`/register\`, and \`/forgot-password\` endpoints to prevent brute-force attacks.
3. **Use Secure Password Hashing:** Ensure passwords are hashed using bcrypt or Argon2. Never store plaintext passwords or use outdated algorithms like MD5.
4. **Secure Session Management:** If using cookies, ensure they have the \`HttpOnly\`, \`Secure\`, and \`SameSite=Lax\` (or \`Strict\`) flags enabled.
5. **Verify Ownership (No IDORs):** Every API endpoint that fetches, modifies, or deletes a resource must verify that the currently authenticated user owns that resource.

## Database & Data Security

6. **Enable Row-Level Security (RLS):** If using a BaaS like Supabase or Firebase, ensure RLS is enabled on all tables and strict policies are enforced.
7. **Use Parameterized Queries:** Prevent SQL injection by never concatenating user input directly into SQL queries. Rely on your ORM or parameterized bindings.
8. **Encrypt Sensitive Data at Rest:** Ensure your database provider encrypts data at rest. For highly sensitive user data (like social security numbers), implement application-level encryption.
9. **Backups:** Verify that automated, daily database backups are running and test the restoration process.
10. **Principle of Least Privilege:** Your application's database user should only have the permissions it strictly needs. It should not be a superuser.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Application Architecture

11. **Sanitize User Input:** Prevent Cross-Site Scripting (XSS) by sanitizing all user-generated content before rendering it in the browser. Avoid \`dangerouslySetInnerHTML\` in React.
12. **Configure CORS Properly:** Do not use \`Access-Control-Allow-Origin: *\`. Explicitly list your frontend domains.
13. **Remove Development Configurations:** Ensure \`DEBUG=False\` in Django, avoid exposing stack traces in Node.js/Next.js, and disable verbose logging in production.
14. **Implement CSRF Protection:** If using cookie-based authentication, ensure CSRF tokens are implemented on all state-changing requests.
15. **Set Security Headers:** Implement Helmet.js (or equivalent) to set headers like \`Content-Security-Policy\`, \`X-Frame-Options\`, and \`Strict-Transport-Security\`.

## Dependencies & Infrastructure

16. **Scan for Vulnerable Dependencies:** Run \`npm audit\` or use a dedicated tool to check for known CVEs in your open-source packages.
17. **Check for Hardcoded Secrets:** Thoroughly scan your repository history to ensure no API keys or database credentials were accidentally committed.
18. **Secure Environment Variables:** Ensure your production environment variables are stored securely in your hosting provider (Vercel, Render, AWS) and are never exposed to the client bundle (e.g., watch out for \`NEXT_PUBLIC_\` leaks).
19. **Protect Cloud Storage:** Ensure your S3 buckets or Supabase Storage containers are private by default. Only allow public access to specific, non-sensitive assets.
20. **Lock Down APIs:** Ensure all internal or admin APIs are completely isolated from public access.

## Operations & Monitoring

21. **Implement Logging:** Log all critical security events (logins, password changes, permission modifications) but ensure you do not log passwords or session tokens.
22. **Set up Alerts:** Configure monitoring tools to alert you of spikes in 500 errors, failed login attempts, or unusual traffic patterns.
23. **Prepare an Incident Response Plan:** Know exactly what steps you will take if a breach occurs (how to shut down the app, rotate keys, and notify users).
24. **Enforce 2FA for Admin Accounts:** Require Two-Factor Authentication on your AWS, Vercel, Stripe, and GitHub accounts.
25. **Run a Full Code Audit:** Use an automated tool to perform a comprehensive security, architecture, and performance review.

<br/>

## Frequently Asked Questions

**Q: Do I really need all 25 points for a small MVP?**
A: Yes. Attackers do not care if you are an MVP. Automated bots scan the entire internet looking for exposed env files, disabled RLS, and missing rate limits.

**Q: How can I check all of this quickly?**
A: CodeAudit.dev automates the majority of this checklist by analyzing your GitHub repository directly.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "vibe-coding-security-risks",
    title: "Vibe Coding Security: What AI Coding Tools Don't Tell You",
    excerpt: "Vibe coding is the fastest way to build software, but relying entirely on AI can lead to disastrous security flaws. Learn the hidden risks of AI generation.",
    category: "AI & Future",
    readTime: "9 min read",
    date: "June 8, 2026",
    seoTitle: "Vibe coding security | CodeAudit.dev",
    seoDescription: "Explore the hidden security risks of vibe coding. Learn what AI coding assistants miss and how to secure your AI-generated applications.",
    content: `
"Vibe coding" is the new paradigm. Instead of meticulously writing logic line-by-line, developers orchestrate applications through high-level prompts, relying on AI models to generate the implementation. It is undeniably powerful and incredibly fast.

But there is a dark side to vibe coding. While the code often works perfectly on the "happy path," it frequently lacks the defensive programming required for production. 

## The Illusion of Competence

AI models are probabilistic engines designed to generate text that looks correct. They excel at pattern matching and syntax generation. However, they lack true contextual understanding of your system's architecture and security posture.

When you ask an AI to "build a billing dashboard," it will confidently generate the React components, the API routes, and the database queries. What it won't do—unless explicitly instructed—is verify that User A cannot view User B's billing history.

## The Most Common "Vibe Coding" Failures

### 1. The Missing Authorization Layer
AI focuses on functionality. It will map the \`/api/invoices/:id\` route directly to a database lookup for that ID. It consistently forgets to assert that the \`user_id\` on the invoice matches the \`user_id\` making the request.

### 2. Leaky Abstractions
When generating full-stack code in frameworks like Next.js, AI often blurs the line between the server and the client. It is notoriously prone to importing server-side utility functions (which might contain secrets or direct database access) into client-side React components.

### 3. The "TODO" Vulnerabilities
AI often leaves placeholders for complex security logic. You might find comments like \`// TODO: Add robust validation here\` buried in a 500-line generated file. In the rush of vibe coding, these comments are easily missed, and the code goes to production without validation.

## How to Secure the Vibe Coding Workflow

You don't need to stop using AI assistants, but you do need to change your workflow. You are no longer just a programmer; you are an auditor and an orchestrator.

1. **Prompt for Security:** Explicitly include security constraints in your prompts. Instead of "Create an update user endpoint," use "Create an update user endpoint. Ensure the user is authenticated, validate the input using Zod, and ensure they can only update their own record."
2. **Isolate Code Reviews:** Do not let the AI that wrote the code review the code. Use a specialized static analysis tool designed to catch structural flaws.
3. **Audit Before Deployment:** Vibe coding creates massive amounts of code quickly. Human review often can't keep up. You must introduce automated security and architecture audits into your CI/CD pipeline.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: Will AI eventually stop writing insecure code?**
A: Models are improving, but as long as they are trained on human code (which is often insecure) and prioritize functional output over defensive constraints, automated auditing will remain a necessity.

**Q: What is the best way to review AI code?**
A: Treat AI-generated code as if it was written by an untrusted third-party contractor. Review the architectural boundaries, authorization logic, and data validation rigorously.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "code-audit-vs-pentest-vs-code-review",
    title: "Code Audit vs Penetration Test vs Code Review: What Do You Need?",
    excerpt: "Confused about the different types of security assessments? Learn the differences between code audits, pentests, and peer reviews, and when to use each.",
    category: "Guides",
    readTime: "6 min read",
    date: "June 5, 2026",
    seoTitle: "Code audit vs pentest vs code review | CodeAudit.dev",
    seoDescription: "Understand the differences between a code audit, a penetration test, and a code review to choose the right security assessment for your software.",
    content: `
As your software project grows, the need for security validation becomes undeniable. But the security industry is full of overlapping jargon. Should you get a code audit? Hire a penetration tester? Rely on internal code reviews?

Understanding the differences between these three approaches is critical to allocating your resources effectively and actually securing your application.

## 1. Internal Code Review

**What it is:** The day-to-day process where developers on your team review each other's pull requests before merging them into the main branch.

**The Focus:** Code style, logic errors, architectural consistency, and basic functionality.

**The Pros:**
- Happens continuously.
- Catches domain-specific business logic errors.
- Shares knowledge across the team.

**The Cons:**
- Highly dependent on the reviewer's security expertise.
- Review fatigue often leads to "LGTM" (Looks Good To Me) on large PRs without deep scrutiny.
- Rarely catches complex architectural vulnerabilities.

## 2. Automated Code Audit (Static Analysis)

**What it is:** An automated, deep scan of your entire repository's source code, looking for known vulnerability patterns, exposed secrets, dependency issues, and technical debt. This is what CodeAudit.dev provides.

**The Focus:** Finding structural vulnerabilities (SQL injection, XSS), hardcoded secrets, misconfigurations, and performance bottlenecks without needing to run the application.

**The Pros:**
- Incredibly fast (minutes, not weeks).
- Objective and comprehensive; it looks at every single line of code.
- Can be integrated directly into your CI/CD pipeline to block bad code automatically.
- Highly cost-effective.

**The Cons:**
- Cannot test runtime environment misconfigurations.
- May produce false positives that require human triage.

## 3. Penetration Test (Pentest)

**What it is:** A manual security assessment performed by ethical hackers. They attempt to breach your live, running application using the same techniques malicious actors use.

**The Focus:** Exploiting business logic flaws, bypassing authentication mechanisms, chaining multiple minor vulnerabilities into a major exploit, and testing server infrastructure.

**The Pros:**
- Tests the application exactly as it exists in the real world.
- Excellent at finding complex business logic flaws (e.g., manipulating cart totals).
- Required by many enterprise compliance frameworks (SOC2, HIPAA).

**The Cons:**
- Extremely expensive (often $10,000 to $50,000+).
- Slow to organize and execute.
- Only provides a snapshot in time; the day after the pentest, new code might introduce new bugs.

## Which One Do You Need?

You don't choose just one; they are complementary layers of defense.

1. **Every Day:** Enforce internal **Code Reviews** for all PRs.
2. **Every Commit:** Run an **Automated Code Audit** to catch secrets, injections, and architectural flaws instantly.
3. **Annually (or before enterprise launch):** Commission a **Penetration Test** to validate your live environment and satisfy compliance requirements.

By utilizing a tool like CodeAudit.dev continuously, you ensure that when you do pay for an expensive pentest, the hackers aren't wasting time finding easily avoidable bugs, and can instead focus on complex business logic.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: Can a code audit replace a pentest for SOC2 compliance?**
A: Usually, no. SOC2 typically requires a manual penetration test of the live environment. However, a code audit is essential preparation to ensure you pass the pentest smoothly.

**Q: Do I need a code audit if I use GitHub Advanced Security?**
A: GitHub provides great foundational scanning, but tools like CodeAudit.dev offer deeper context, performance analysis, architecture reviews, and AI-specific flaw detection tailored to modern stacks like Next.js and Supabase.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "reduce-nextjs-bundle-size",
    title: "How to Reduce JavaScript Bundle Size in Next.js",
    excerpt: "Is your Next.js application suffering from slow load times? Learn actionable strategies to analyze and significantly reduce your JavaScript bundle size.",
    category: "Performance",
    readTime: "8 min read",
    date: "June 2, 2026",
    seoTitle: "Reduce Next.js bundle size | CodeAudit.dev",
    seoDescription: "Discover proven strategies to analyze and reduce your Next.js JavaScript bundle size, improving Core Web Vitals and user experience.",
    content: `
Next.js provides a fantastic developer experience, but if you aren't careful, it's incredibly easy to ship massive JavaScript bundles to your users. Large bundles lead to slow Time to Interactive (TTI), poor Core Web Vitals, and frustrated users on mobile devices.

Here is a comprehensive guide to identifying bundle bloat and fixing it in your Next.js application.

## 1. Analyze Your Current Bundle

You cannot fix what you cannot measure. The first step is to see exactly what is taking up space.

Install the \`@next/bundle-analyzer\` package:
\`\`\`bash
npm install @next/bundle-analyzer
\`\`\`

Update your \`next.config.js\`:
\`\`\`javascript
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});
module.exports = withBundleAnalyzer({});
\`\`\`

Run the analyzer:
\`\`\`bash
ANALYZE=true npm run build
\`\`\`
This will open a visual treemap in your browser. Look for massive colored blocks. Common offenders include \`lodash\`, \`moment\`, \`framer-motion\`, and large UI libraries.

## 2. Dynamic Imports for Heavy Components

If a component is not needed on the initial page load (e.g., a modal, a complex chart, or a heavy rich-text editor), do not include it in the main bundle. Use Next.js dynamic imports.

\`\`\`javascript
import dynamic from 'next/dynamic'

// This component will only be loaded when it is rendered
const HeavyChart = dynamic(() => import('../components/HeavyChart'), {
  loading: () => <p>Loading chart...</p>,
  ssr: false // Optional: disable server-side rendering if it relies on browser APIs
})
\`\`\`

## 3. Replace Heavy Dependencies

Many popular libraries have modern, lightweight alternatives.

- Replace **Moment.js** (massive, mutable) with **date-fns** or **Day.js**.
- Replace full **Lodash** imports (\`import _ from 'lodash'\`) with specific function imports (\`import get from 'lodash/get'\`), or use native JavaScript array/object methods.
- If you only use one icon from a massive icon library, ensure you are importing it directly rather than pulling in the entire set.

## 4. Leverage React Server Components (App Router)

If you are using the Next.js App Router, take full advantage of React Server Components (RSC). 

By default, components in the \`app\` directory are Server Components. Their dependencies are **never sent to the client bundle**. Only add the \`"use client"\` directive when you absolutely need interactivity (hooks, state, or event listeners).

Push interactivity down the tree. Don't make an entire page a Client Component just because you need a button to track state; extract the button into its own Client Component and keep the rest of the page server-rendered.

## 5. Optimize Third-Party Scripts

Marketing tags, analytics, and customer support widgets can ruin your performance. 

Always use the Next.js \`Script\` component instead of raw \`<script>\` tags, and use the appropriate \`strategy\`:
- \`strategy="afterInteractive"\` for analytics.
- \`strategy="lazyOnload"\` for chat widgets or heavy scripts that aren't critical.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: What is a good bundle size?**
A: Aim for a First Load JS of less than 150KB for static pages, and try to keep even complex interactive pages under 300KB parsed (not compressed).

**Q: Does CodeAudit check for performance issues?**
A: Yes. CodeAudit's Performance Analyzer specifically flags large bundles, inefficient imports, and components that should be dynamically loaded.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "jwt-secret-hardcoded-fix",
    title: "JWT Secret Hardcoded in Source Code: Risk and Fix",
    excerpt: "A hardcoded JWT secret means complete compromise of your authentication system. Learn why this happens and how to securely manage JWT signing keys.",
    category: "Security",
    readTime: "5 min read",
    date: "May 28, 2026",
    seoTitle: "JWT secret hardcoded fix | CodeAudit.dev",
    seoDescription: "Discover the critical risks of hardcoding JWT secrets in your source code and learn how to properly secure your authentication tokens.",
    content: `
JSON Web Tokens (JWTs) are the backbone of modern stateless authentication. They allow your server to verify user identity without querying a database on every request. However, the entire security of a JWT system relies on a single string: the signing secret.

If an attacker obtains your JWT secret, they can forge valid authentication tokens for any user in your system, including administrators, bypassing the login screen entirely.

## The Problem: Hardcoded Secrets

During development, it is common to hardcode a string to get authentication working quickly:

\`\`\`javascript
// DANGEROUS CODE
const token = jwt.sign(
  { userId: user.id }, 
  'my_super_secret_dev_key', // Hardcoded secret
  { expiresIn: '1h' }
);
\`\`\`

If this code makes it into a git commit, your application is compromised. Even if the repository is private, code can be leaked, employees leave, and backups can be exposed.

## The Fix: Environment Variables

The signing secret must **never** exist in your source code. It must be injected at runtime via environment variables.

### Step 1: Update Your Code
Modify your token generation and verification logic to read from \`process.env\`.

\`\`\`javascript
// SECURE CODE
if (!process.env.JWT_SECRET) {
  throw new Error("FATAL: JWT_SECRET environment variable is not set.");
}

const token = jwt.sign(
  { userId: user.id }, 
  process.env.JWT_SECRET, 
  { expiresIn: '1h' }
);
\`\`\`

### Step 2: Set the Variable
Generate a strong, cryptographically secure random string. Do not use words or easily guessable phrases.
\`\`\`bash
# Generate a secure 64-character hex string
openssl rand -hex 32
\`\`\`
Add this string to your production environment variables in your hosting provider (e.g., Vercel, AWS, Render).

### Step 3: Rotate the Compromised Key
If your key was hardcoded in production, **you must rotate it immediately**. Change the \`JWT_SECRET\` in your environment variables. 
*Note: Rotating the key will invalidate all existing user sessions, forcing everyone to log in again. This is disruptive, but strictly necessary.*

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: Can I use the same secret for development and production?**
A: Never. Your local development environment should use a dummy secret (e.g., \`dev_secret_only\`), while production must use a cryptographically secure, hidden key.

**Q: How does CodeAudit help?**
A: CodeAudit automatically scans your entire codebase for hardcoded secrets, including JWT keys, API tokens, and database passwords, alerting you before they reach production.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  },
  {
    slug: "supabase-rls-security-checklist",
    title: "Supabase RLS: A Security Checklist Before You Launch",
    excerpt: "Supabase exposes your database directly to the client. If you don't configure Row-Level Security (RLS) correctly, your entire database is vulnerable.",
    category: "Guides",
    readTime: "7 min read",
    date: "May 25, 2026",
    seoTitle: "Supabase RLS security checklist | CodeAudit.dev",
    seoDescription: "A comprehensive security checklist for configuring Supabase Row-Level Security (RLS) to ensure your database is protected from unauthorized access.",
    content: `
Supabase is an incredible platform that accelerates development by providing an auto-generated REST API directly on top of your PostgreSQL database. This architecture is powerful, but it completely shifts the security paradigm. 

Instead of writing backend endpoints to validate user permissions, you must rely entirely on PostgreSQL Row-Level Security (RLS). If RLS is misconfigured, anyone with your public \`anon\` key can read, modify, or delete your entire database.

Use this checklist to secure your Supabase project before launching.

## 1. Enable RLS on Every Table
By default, newly created tables in Supabase have RLS disabled. This means they are completely public.

**Check:** Go to the Supabase Dashboard -> Authentication -> Policies, and ensure every table shows "RLS Enabled". Alternatively, run this SQL:
\`\`\`sql
ALTER TABLE your_table ENABLE ROW LEVEL SECURITY;
\`\`\`

## 2. Default to Deny All
When RLS is enabled, the default behavior is to deny all access unless a specific policy grants it. Ensure you have not accidentally created an overly permissive generic policy like \`true\` for all operations.

## 3. Write Explicit SELECT, INSERT, UPDATE, and DELETE Policies
A common mistake is granting \`ALL\` privileges based on a simple check. It is much safer to write discrete policies for each operation.

For example, a user might be able to \`SELECT\` any post, but only \`UPDATE\` or \`DELETE\` their own posts.

\`\`\`sql
-- Example: Users can only update their own profiles
CREATE POLICY "Users can update own profile" 
ON profiles 
FOR UPDATE 
USING (auth.uid() = id);
\`\`\`

## 4. Protect Your Service Role Key
The \`service_role\` key bypasses RLS completely. It is designed for backend administrative tasks.
**Check:** Ensure the \`service_role\` key is NEVER exposed in your frontend code. It should only reside in secure backend environments or Edge Functions.

## 5. Validate Input in Triggers
RLS handles authorization (who can access data), but it does not handle validation (is the data formatted correctly).
**Check:** If users can insert data directly from the client, use PostgreSQL check constraints or trigger functions to ensure fields like \`email_address\` or \`age\` contain valid data.

## 6. Secure Storage Buckets
Supabase Storage also relies on RLS. If you have a bucket for user avatars, ensure policies dictate who can read and upload to that bucket.
**Check:** Verify that your "private" documents bucket does not have a public read policy.

<br/>

Want CodeAudit to check your repo for this automatically? Join the waitlist.

## Frequently Asked Questions

**Q: Does RLS affect performance?**
A: RLS policies add a small overhead to every query. Keep policies simple and avoid complex subqueries within the policy definition to maintain high performance.

**Q: Can I test my RLS policies?**
A: Yes, you can use the Supabase dashboard to simulate queries as different users, or write unit tests using the \`pgTAP\` extension. CodeAudit also statically analyzes your migration files to detect missing RLS.

Want CodeAudit to check your repo for this automatically? Join the waitlist.
`
  }
];
